# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Mark Dean
email: mdean@bnl.gov
description: > # this means to ignore newlines until "url:"
  Resonant x-ray scattering on quantum materials at Brookhaven.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Design update from Qin Yao.

url: "https://markdean.info" # the base hostname & protocol for your site
baseurl: "" # was /me previoulsy /al-folio # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: mpmdean # your GitHub user name
#_QY twitter_username: # your Twitter handle
#_QY linkedin_username: # your LinkedIn user name
scholar_userid: mpmdean@gmail.com # your Google Scholar ID
orcid_id: 0000-0001-5139-3543 # your ORCID ID
#_QY medium_username: # your Medium username
#_QY quora_username: # your Quora username

contact_note: >
  Email is usually the best way to reach me.

#_QY google_analytics: UA-XXXXXXXXX # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
#_QY blog_name: Updates
#_QY blog_description: what is going on with Mark's research

# Pagination
#_QY paginate: 4
#_QY permalink: /blog/:year/:title/
#_QY paginate_path: /blog/page:num/

#_QY text:
#_QY   pagination:
#_QY     newer: 'Newer'
#_QY     older: 'Older'

# Comments
#_QY disqus_shortname: al-folio_what? # put your disqus shortname

# Optional features
#_QY show_social_icons:  false
#_QY enable_anchorjs:    false
#_QY enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  people:
    output: true
    permalink: /people/:path/
  groupnotes:
    output: true
    permalink: /groupnotes/:path/
  research:
    output: true
    permalink: /resesarch/:path/
news_limit: 12

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Dean

  style: american-physics-society
  locale: en

  sort_by: year, month
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
